### ISSUE TITLE
Problem with two coexisting CKKS crypto contexts with different ring dimensions 

### ISSUE THREAD

**Issue by aehud** [openfheorg/openfhe-development#323] opened 2023-03-06 11:49 UTC
The following code produces the wrong result.
It creates two contexts, cc1 and cc2. Then uses cc1 to encrypt and decrypt. The result after decryption turns out wrong.
The problem goes away if cc2 is commented out.

```
// Setup crypto context 1
  CCParams<CryptoContextCKKSRNS> parameters;
  parameters.SetMultiplicativeDepth(5);
  parameters.SetScalingModSize(40);
  parameters.SetRingDim(4096 * 4);
  parameters.SetBatchSize(32); 
  CryptoContext<lbcrypto::DCRTPoly> cc1 = GenCryptoContext(parameters);
  cc1->Enable(PKE);
  cc1->Enable(KEYSWITCH);
  cc1->Enable(LEVELEDSHE);
  lbcrypto::KeyPair<lbcrypto::DCRTPoly> kk1 = cc1->KeyGen();

  // Setup crypto context 2, not used
  CCParams<CryptoContextCKKSRNS> parameters2;
  parameters2.SetMultiplicativeDepth(1);
  parameters2.SetScalingModSize(30);
  parameters2.SetRingDim(16); 
  parameters2.SetBatchSize(4);
  parameters2.SetSecurityLevel(HEStd_NotSet);
  CryptoContext<lbcrypto::DCRTPoly> cc2 = GenCryptoContext(parameters2);
  cc2->Enable(PKE);
  cc2->Enable(KEYSWITCH);
  cc2->Enable(LEVELEDSHE);

  lbcrypto::KeyPair<lbcrypto::DCRTPoly> kk2 = cc2->KeyGen();

  // Encrypt
  vector<double> x = {1.0, 1.1, 1.2};
  Plaintext ptxt = cc1->MakeCKKSPackedPlaintext(x);
  auto c = cc1->Encrypt(ptxt, kk1.publicKey);
  // Decrypt
  Plaintext result;
  cc1->Decrypt(c, kk1.secretKey, &result);
  vector<double> rx = result->GetRealPackedValue();
  // Result comes out wrong (not near 1,1.1.1.2)
  std::cout << "res = " << rx[0] << "," << rx[1] << "," << rx[2] << std::endl;
```

**Comment by dsuponitskiy** [comment] 2023-05-22 18:44
The problem is that the DiscreteFourierTransform class (core/include/math/dftransform.h) includes some static variables that get reassigned when a new cryptocontext is created. They are
static size_t m_M;
static size_t m_Nh;
They get a new value from ringDimension.

As DiscreteFourierTransform seems to be used in the code related to a particular cryptocontext, we need to decide on whether it  makes sense to refactor DiscreteFourierTransform to a regular class and keep its object in CryptoContext.

**Comment by yspolyakov** [comment] 2023-06-27 20:00
Switch from the use of static methods and data members for DiscreteFourierTransform to normal C++ objects instantiated from the modified DiscreteFourierTranform class.

**Closed** 2023-07-06 18:07 UTC
Labels: bug, Priority: LOW
