### ISSUE TITLE
Verbose error in case of segfault due to exceeding multiplicative depth

### ISSUE THREAD

**Issue by jtakeshi-nd** [openfheorg/openfhe-development#355] opened 2023-04-09 22:26 UTC
KeySwitchHYBRID::EvalFastKeySwitchCore may segfault in case of a shortage of multiplicative depth in CKKS. This is due to KeySwitchHYBRID::EvalKeySwitchPrecomputeCore returning a (shared_ptr to a) vector of length zero, which happens when the variable numPartQl is zero. The root cause of this is an application whose depth exceeds the allotted depth of the CKKS parameters.

Instead of segfaulting, this case can be checked for (at any of EvalFastKeySwitchCore, EvalKeySwitchPrecomputeCore, or KeySwitchCore), and an informative exception can be thrown, helping the user to understand the cause of the segfault.

**Comment by caesaretos** [comment] 2023-04-25 20:16
The issue is fixed by preventing DropLastElement from dropping elements of a DCRTPoly with 1 or fewer elements.

**Closed** 2023-04-28 18:24 UTC
Labels: bug
